/**
 * 루트 레이아웃 컴포넌트
 * 애플리케이션의 전역 레이아웃과 메타데이터를 정의
 */

import type { Metadata } from "next";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next";
import type React from "react";
import { Providers } from "@/lib/providers";

// 페이지 메타데이터 설정
export const metadata: Metadata = {
  title: "Assetify Desk",
  description: "Generated by create next app",
};

/**
 * 루트 레이아웃 컴포넌트
 * 모든 페이지에 공통으로 적용되는 레이아웃
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="antialiased">
        {/* Vercel 애널리틱스 */}
        <Analytics />
        {/* 전역 상태 관리 프로바이더 */}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
